### ISSUE TITLE
Implement Numeral.js

### ISSUE THREAD

**Issue by nkmlombardi** [blockstreet/interface#13]
http://numeraljs.com/

Currently, the site uses a few util functions to do conversion of JavaScript Number types, to human readable currency strings. NumeralJS would allow us to use one consistent library for all currency conversion. It would also pave the way for future locale-based currency (EUR, USD, etc).

**Comment by allen-fdes** [comment]
@nkmlombardi can I start on this?

**Comment by nkmlombardi** [comment]
Hey @allen-fdes of course! If you'd like to hop into our Slack channel I'd love to meet you. Might be good to get in touch before starting.
