### ISSUE TITLE
High charts graph disappears when you zoom in too far

### ISSUE THREAD

**Issue by Suhmedoh** [blockstreet/interface#15]
When zooming in on any crypto, if you zoom in too far, the whole char disappears and you have to click a different crypto then click back to see it again, zoomed out

**Comment by protocol114** [comment]
I think I can reproduce - I zoomed in as close as I could, and after a while it eventually blurred and said "No price history data for Bitcoin." I had to click a different coin and come back to solve.

Is that the same as what you're describing?

**Comment by nkmlombardi** [comment]
When you select one of the zoom options, if the zoom warrants a different time series interval (minutely, hourly, daily), then it makes a request to the backend and new data is swapped into the graph.

We need to look into a better solution than that.

**Comment by Suhmedoh** [comment]
When i zoomed, there was no message, the bottom bar's sliders disappeared,
and the main portion of the graph was completely blank． perhaps a maximum
zoom in limit could be implemented?

**Comment by nkmlombardi** [comment]
Yeah the highcharts configuration needs a minimum zoom limit.

**Comment by nsocrates** [comment]
It seems like after a certain interval, the API call returns an empty array; that empty array is being used to redraw the graph. I can add a condition to prevent this from happening and prevent further API calls on the same endpoint.

**Comment by nkmlombardi** [comment]
The simplest solution is to set this in the highcharts configuration:

```
        xAxis: {
            minRange: 24 * 3600 * 1000
        }
```

The above is a minimum zoom of 24 hours, which Coin Market Cap uses. It think that would be the best setting for us as well.

**Comment by nsocrates** [comment]
You are right. That is a better solution. We may also have to use `afterSetExtremes` instead of `setExtremes`, since the min/max values are corrected for minRange.

**Comment by nkmlombardi** [comment]
I was discussing this with Jay earlier as he was going through the issue...

The problem is that we only store 7 days worth of data on the hourly interval. If the user's selected zoom starts before then, or is in a range between then, the back-end api returns an empty array (as it should). There's a function in the ticker page component:

```
        calculateHistoryInterval(duration) {
            if (duration.asDays() > 7 && duration.asDays() <= 31) return 'hourly'
            else if (duration.asDays() > 1 && duration.asDays() <= 7) return 'hourly'
            else if (duration.asDays() <= 1) return 'minutely'
            return 'daily'
        },
```

That determines what interval the data pulled should be, this needs an if condition at the top that detected if the start of the range is more than 7 days ago.

**Comment by nsocrates** [comment]
Will something like this work? I'm adding it in the `zoom` function:

```
  const diffDays = moment.duration(moment().diff(moment(event.min))).asDays()
  const isNotDaily = this.expanded.interval !== 'daily'
  if (diffDays > 7 && isNotDaily) {
      return
  }
```

**Comment by nkmlombardi** [comment]
This issue was solved using the new proxy to coinmarketcap method.
